//Destroy.....
//personalizado por nevi-dev
const roles = {
  '*Cría de Tiburón V*🦈': 0,
  '*Cría de Tiburón IV*🦈': 2,
  '*Cría de Tiburón III*🦈': 4,
  '*Cría de Tiburón II*🦈': 6,
  '*Cría de Tiburón I*🦈': 8,
  '*Vigía de la Costa V*🌊': 10,
  '*Vigía de la Costa IV*🌊': 12,
  '*Vigía de la Costa III*🌊': 14,
  '*Vigía de la Costa II*🌊': 16,
  '*Vigía de la Costa I*🌊': 18,
  '*Cazador(a) Silencioso/a V*🤫': 20,
  '*Cazador(a) Silencioso/a IV*🤫': 22,
  '*Cazador(a) Silencioso/a III*🤫': 24,
  '*Cazador(a) Silencioso/a II*🤫': 26,
  '*Cazador(a) Silencioso/a I*🤫': 28,
  '*Aleta de Acero V*🔪': 30,
  '*Aleta de Acero IV*🔪': 32,
  '*Aleta de Acero III*🔪': 34,
  '*Aleta de Acero II*🔪': 36,
  '*Aleta de Acero I*🔪': 38,
  '*Corriente Letal V*🌀': 40,
  '*Corriente Letal IV*🌀': 42,
  '*Corriente Letal III*🌀': 44,
  '*Corriente Letal II*🌀': 46,
  '*Corriente Letal I*🌀': 48,
  '*Depredador(a) de Élite V*🔱': 50,
  '*Depredador(a) de Élite IV*🔱': 52,
  '*Depredador(a) de Élite III*🔱': 54,
  '*Depredador(a) de Élite II*🔱': 56,
  '*Depredador(a) de Élite I*🔱': 58,
  '*Danza del Frenesí V*🩸': 60,
  '*Danza del Frenesí IV*🩸': 62,
  '*Danza del Frenesí III*🩸': 64,
  '*Danza del Frenesí II*🩸': 66,
  '*Danza del Frenesí I*🩸': 68,
  '*Tiburón Tigre Impecable V*🐅': 70,
  '*Tiburón Tigre Impecable IV*🐅': 72,
  '*Tiburón Tigre Impecable III*🐅': 74,
  '*Tiburón Tigre Impecable II*🐅': 76,
  '*Tiburón Tigre Impecable I*🐅': 78,
  '*Mandíbula de la Victoria V*🏆': 80,
  '*Mandíbula de la Victoria IV*🏆': 85,
  '*Mandíbula de la Victoria III*🏆': 90,
  '*Mandíbula de la Victoria II*🏆': 95,
  '*Mandíbula de la Victoria I*🏆': 99,
  '*Furia del Abismo V*🌌': 100,
  '*Furia del Abismo IV*🌌': 110,
  '*Furia del Abismo III*🌌': 120,
  '*Furia del Abismo II*🌌': 130,
  '*Furia del Abismo I*🌌': 140,
  '*El Gran Blanco V*👑': 150,
  '*El Gran Blanco IV*👑': 160,
  '*El Gran Blanco III*👑': 170,
  '*El Gran Blanco II*👑': 180,
  '*El Gran Blanco I*👑': 199,
  '*Tsunami Viviente V*🌊': 200,
  '*Tsunami Viviente IV*🌊': 225,
  '*Tsunami Viviente III*🌊': 250,
  '*Tsunami Viviente II*🌊': 275,
  '*Tsunami Viviente I*🌊': 299,
  '*Torpedo Humano/a V*🚀': 300,
  '*Torpedo Humano/a IV*🚀': 325,
  '*Torpedo Humano/a III*🚀': 350,
  '*Torpedo Humano/a II*🚀': 375,
  '*Torpedo Humano/a I*🚀': 399,
  '*Terror de los Océanos V*💀': 400,
  '*Terror de los Océanos IV*💀': 425,
  '*Terror de los Océanos III*💀': 450,
  '*Terror de los Océanos II*💀': 475,
  '*Terror de los Océanos I*💀': 499,
  '*Megalodón Primordial V*🦴': 500,
  '*Megalodón Primordial IV*🦴': 525,
  '*Megalodón Primordial III*🦴': 550,
  '*Megalodón Primordial II*🦴': 575,
  '*Megalodón Primordial I*🦴': 599,
  '*Encarnación de la Caza V*🎯': 600,
  '*Encarnación de la Caza IV*🎯': 625,
  '*Encarnación de la Caza III*🎯': 650,
  '*Encarnación de la Caza II*🎯': 675,
  '*Encarnación de la Caza I*🎯': 699,
  '*Ellen Joe, Apex Oceánico V*🌊': 700,
  '*Ellen Joe, Apex Oceánico IV*🌊': 725,
  '*Ellen Joe, Apex Oceánico III*🌊': 750,
  '*Ellen Joe, Apex Oceánico II*🌊': 775,
  '*Ellen Joe, Apex Oceánico I*🌊': 799,
  '*El Diluvio Implacable V*⛈️': 800,
  '*El Diluvio Implacable IV*⛈️': 825,
  '*El Diluvio Implacable III*⛈️': 850,
  '*El Diluvio Implacable II*⛈️': 875,
  '*El Diluvio Implacable I*⛈️': 899,
  '*Calamidad de las Profundidades V*🐙': 900,
  '*Calamidad de las Profundidades IV*🐙': 925,
  '*Calamidad de las Profundidades III*🐙': 950,
  '*Calamidad de las Profundidades II*🐙': 975,
  '*Calamidad de las Profundidades I*🐙': 999,
  '*🌟 El Gran Majestad de los Mares 🌟*': 1000,
  '*🌟 El Gran Majestad II 🌟*': 2000,
  '*🌟 El Gran Majestad III 🌟*': 3000,
  '*🌟 El Gran Majestad IV 🌟*': 4000,
  '*🌟 El Gran Majestad V 🌟*': 5000,
  '*👑 Ellen Joe: Depredador Alfa 👑*': 10000
}

let handler = m => m
handler.before = async function (m, { conn }) {
  let user = db.data.users[m.sender]
  if (!user) return
  let level = user.level
  let role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0]
  user.role = role
  return true
}
export default handler
