const MIDDLE_GROUP = '120363404169868595@g.us';
const TRADE_GROUP_LINK = 'https://chat.whatsapp.com/EOXX9bNd5hMGKBdT7AgxlC?mode=ems_copy_t';
const TRADE_GROUP_ID = '120363403658322060@g.us';
const TRADE_PIC_URL = 'https://i.ibb.co/DHSzNJLp/Pretty-boya-animewallpapers-animeicons-boys.jpg';
const TRADE_FINAL_WAIT = 10 * 60 * 1000; // 10 minutos

const TRADE_RULES = `El trade se realizará en este momento, están siendo supervisados, cualquier intento de estafa o que detectemos algo raro, va automáticamente baneado y con reputación quemada hasta las patas, espero disfruten su trade :D

*¿En qué consiste el middleman?*

Un middleman es un intermediario de confianza el cual se encarga de tomar las cosas de los participantes que intercambian para permitir un ambiente seguro en nuestro grupo, aunque algunos suelen ser medio especiales y diferentes a la manera de tradear.`;

global.currentTrades = global.currentTrades || {};

// === COMANDO PARA SOLICITAR TRADE ===
let handler = async (m, { conn }) => {
    const from = m.chat;
        const user1 = m.sender;
            const user2 = (m.mentionedJid && m.mentionedJid[0]) ? m.mentionedJid[0] : null;

                if (!user2) return conn.reply(from, '⚠️ Menciona a la persona para el trade.', m);
                    if (global.currentTrades[from]) return conn.reply(from, '⚠️ Ya hay un trade activo en este grupo.', m);

                        global.currentTrades[from] = { requester: user1, partner: user2, taken: false };

                            // Enviar solicitud al grupo de middlemen
                                await conn.sendMessage(MIDDLE_GROUP, {
                                        text: `📩 *Nuevo trade desde:* ${from}\n👤 Solicitante: @${user1.split('@')[0]}\n👤 Participante: @${user2.split('@')[0]}\nPulsa el botón o escribe "si" para aceptar.`,
                                                mentions: [user1, user2],
                                                        buttons: [{ buttonId: `accept_${from}`, buttonText: { displayText: '✅ Aceptar Trade' }, type: 1 }],
                                                                headerType: 1
                                                                    });

                                                                        await conn.reply(from, '⌛ Buscando middleman disponible... espera la confirmación.', m);
                                                                        };

                                                                        handler.help = ['middleman'];
                                                                        handler.tags = ['tools'];
                                                                        handler.command = ['middleman'];
                                                                        export default handler;

                                                                        // === LISTENER GLOBAL PARA BOTÓN O "SI" ===
                                                                        export async function listenTrades(conn) {
                                                                            conn.ev.on('messages.upsert', async ({ messages }) => {
                                                                                    for (let m of messages) {
                                                                                                if (!m.message) continue;

                                                                                                            // Solo escuchar el grupo de middlemen
                                                                                                                        if (m.key.remoteJid !== MIDDLE_GROUP) continue;

                                                                                                                                    const text = m.message.conversation || '';
                                                                                                                                                let buttonId = null;

                                                                                                                                                            // Detectar botón
                                                                                                                                                                        if (m.message.buttonsResponseMessage) {
                                                                                                                                                                                        buttonId = m.message.buttonsResponseMessage.selectedButtonId;
                                                                                                                                                                                                    } else if (m.message.interactiveResponseMessage?.nativeFlowResponseMessage) {
                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                        const json = JSON.parse(m.message.interactiveResponseMessage.nativeFlowResponseMessage.paramsJson);
                                                                                                                                                                                                                                                            buttonId = json.id || json.buttonId || null;
                                                                                                                                                                                                                                                                            } catch {}
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                    const isYes = text.trim().toLowerCase() === 'si';
                                                                                                                                                                                                                                                                                                                if (!isYes && !buttonId?.startsWith('accept_')) continue;

                                                                                                                                                                                                                                                                                                                            const groupId = buttonId ? buttonId.replace('accept_', '') : Object.keys(global.currentTrades)[0];
                                                                                                                                                                                                                                                                                                                                        const trade = global.currentTrades[groupId];
                                                                                                                                                                                                                                                                                                                                                    if (!trade || trade.taken) continue;

                                                                                                                                                                                                                                                                                                                                                                trade.taken = true;

                                                                                                                                                                                                                                                                                                                                                                            // Notificaciones
                                                                                                                                                                                                                                                                                                                                                                                        await conn.sendMessage(MIDDLE_GROUP, { text: `✅ @${m.key.participant.split('@')[0]} aceptó el trade.`, mentions: [m.key.participant] });
                                                                                                                                                                                                                                                                                                                                                                                                    await conn.sendMessage(groupId, { text: `✅ Middleman @${m.key.participant.split('@')[0]} aceptó el trade.\nAquí está el enlace del grupo de trades: ${TRADE_GROUP_LINK}` });

                                                                                                                                                                                                                                                                                                                                                                                                                // Espera 10 minutos antes de enviar botón de "Trade finalizado"
                                                                                                                                                                                                                                                                                                                                                                                                                            trade.timeout = setTimeout(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                            await conn.sendMessage(TRADE_GROUP_ID, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                text: '⌛ Trade en curso, cuando terminen, pulsa el botón para finalizar:',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    buttons: [{ buttonId: 'trade_done', buttonText: { displayText: '✅ Trade finalizado' }, type: 1 }],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headerType: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, TRADE_FINAL_WAIT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // === LISTENER PARA FINALIZAR TRADE ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export async function listenTradeDone(conn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.ev.on('messages.upsert', async ({ messages }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let m of messages) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!m.message || m.key.remoteJid !== TRADE_GROUP_ID) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const buttonId = m.message.buttonsResponseMessage?.selectedButtonId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (buttonId !== 'trade_done') continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await conn.sendMessage(TRADE_GROUP_ID, { text: `✅ Trade finalizado. ${TRADE_RULES}` });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Limpiar trades activos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (let groupId in global.currentTrades) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    clearTimeout(global.currentTrades[groupId]?.timeout);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    delete global.currentTrades[groupId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }