const MIDDLE_GROUP = '120363404169868595@g.us';
const TRADE_GROUP_ID = '120363404331720164@g.us';
const TRADE_GROUP_LINK = 'https://chat.whatsapp.com/HwMqds7geVDFAE1EOulMGi?mode=ems_copy_t';
const WELCOME_DELAY = 1 * 60 * 1000; // 1 minuto
const FINAL_BUTTON_DELAY = 5 * 60 * 1000; // 5 minutos
const LINK_SELF_DESTRUCT = 2 * 60 * 1000; // 2 minutos

const TRADE_RULES = `El trade se realizará en este momento, están siendo supervisados, cualquier intento de estafa o que detectemos algo raro, va automáticamente baneado y con reputación quemada hasta las patas, espero disfruten su trade :D

*¿En qué consiste el middleman?*

Un middleman es un intermediario de confianza el cual se encarga de tomar las cosas de los participantes que intercambian para permitir un ambiente seguro en nuestro grupo, aunque algunos suelen ser medio especiales y diferentes a la manera de tradear.`;

const TRADE_IMAGE_URL = 'https://i.ibb.co/DHSzNJLp/tu-foto.png';

global.currentTrades = global.currentTrades || {};

// === LISTENER PARA ACEPTAR TRADE ===
export async function listenTrades(conn) {
    conn.ev.on('messages.upsert', async ({ messages }) => {
            for (let m of messages) {
                        if (!m.message) continue;
                                    if (m.key.remoteJid !== MIDDLE_GROUP) continue;

                                                const text = m.message.conversation || '';
                                                            let buttonId = null;

                                                                        if (m.message.buttonsResponseMessage) {
                                                                                        buttonId = m.message.buttonsResponseMessage.selectedButtonId;
                                                                                                    }

                                                                                                                const isYes = text.trim().toLowerCase() === 'si';
                                                                                                                            if (!isYes && !buttonId?.startsWith('accept_')) continue;

                                                                                                                                        const groupId = buttonId ? buttonId.replace('accept_', '') : Object.keys(global.currentTrades)[0];
                                                                                                                                                    const trade = global.currentTrades[groupId];
                                                                                                                                                                if (!trade || trade.taken) continue;

                                                                                                                                                                            trade.taken = true;

                                                                                                                                                                                        // Mensaje a middlemen
                                                                                                                                                                                                    const msgMiddle = await conn.sendMessage(MIDDLE_GROUP, {
                                                                                                                                                                                                                    image: { url: TRADE_IMAGE_URL },
                                                                                                                                                                                                                                    caption: `✅ @${m.key.participant.split('@')[0]} aceptó el trade.\nEnlace del grupo de trades (destruirá en 2 min): ${TRADE_GROUP_LINK}`,
                                                                                                                                                                                                                                                    mentions: [m.key.participant],
                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                            // Mensaje a participantes
                                                                                                                                                                                                                                                                                        const mentions = [trade.requester, trade.partner];
                                                                                                                                                                                                                                                                                                    const msgTrade = await conn.sendMessage(groupId, {
                                                                                                                                                                                                                                                                                                                    image: { url: TRADE_IMAGE_URL },
                                                                                                                                                                                                                                                                                                                                    caption: `✅ Middleman @${m.key.participant.split('@')[0]} aceptó el trade.\nEnlace del grupo de trades (destruirá en 2 min): ${TRADE_GROUP_LINK}`,
                                                                                                                                                                                                                                                                                                                                                    mentions,
                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                            // Autodestruir mensajes tras 2 minutos
                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                        await conn.sendMessage(MIDDLE_GROUP, { delete: msgMiddle.key });
                                                                                                                                                                                                                                                                                                                                                                                                                        await conn.sendMessage(groupId, { delete: msgTrade.key });
                                                                                                                                                                                                                                                                                                                                                                                                                                    }, LINK_SELF_DESTRUCT);

                                                                                                                                                                                                                                                                                                                                                                                                                                                // Mensaje de bienvenida + reglas 1 minuto después
                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await conn.sendMessage(TRADE_GROUP_ID, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                image: { url: TRADE_IMAGE_URL },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    caption: `📢 Bienvenidos al grupo de trade!\n\n${TRADE_RULES}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, WELCOME_DELAY);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Botón "Trade finalizado" 5 minutos después
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trade.timeout = setTimeout(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await conn.sendMessage(TRADE_GROUP_ID, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            text: '⌛ Trade en curso, cuando terminen, pulsa el botón para finalizar:',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                buttons: [{ buttonId: 'trade_done', buttonText: { displayText: '✅ Trade finalizado' }, type: 1 }],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headerType: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, FINAL_BUTTON_DELAY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // === LISTENER PARA FINALIZAR TRADE ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export async function listenTradeDone(conn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                conn.ev.on('messages.upsert', async ({ messages }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let m of messages) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!m.message || m.key.remoteJid !== TRADE_GROUP_ID) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const buttonId = m.message.buttonsResponseMessage?.selectedButtonId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (buttonId !== 'trade_done') continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Solo aviso final de que deben salir, sin repetir reglas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await conn.sendMessage(TRADE_GROUP_ID, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    text: `✅ Trade finalizado.\nPor favor, todos los participantes deben salir del grupo por su cuenta.`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Limpiar trades activos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let groupId in global.currentTrades) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clearTimeout(global.currentTrades[groupId]?.timeout);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        delete global.currentTrades[groupId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }